# Apply your stack customization here. This file is not tracked by git.

# If you want to make persistent changes to this file you can do so by using
# `git update-index --no-assume-unchanged values-overrides.yaml` command,
# commiting changes, and then disabling file tracking by running
# `git update-index --assume-unchanged values-overrides.yaml` command.

prometheus:
  # Configuration options in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.RemoteWriteSpec
  retention: 1h
  remoteWrite:
  - url: http://tobs-promscale.bench.svc:9201/write
    remoteTimeout: 100s
    # Configuration options in https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#queueconfig
    queueConfig:
      maxShards: 40
      maxSamplesPerSend: 10000
  resources:
    requests:
      # cpu: 17
      # memory: 65Gi

avalanche:
  serviceMonitor:
    interval: 50s
  replicaCount: 1
  fakePrometheusTargetCount: 1
  extraArgs:
    - --series-interval=315360000
    - --metric-interval=315360000
    # Total number of time series generated by avalanche is equal to
    #   metric-count * series-count
    # Which is 500K series here by default. This translates to a load
    # of 10K samples / second per replica, with a scrape interval of
    # 50s by Prometheus.
    # To increase the active series, we can simply increase the value of
    # fakePrometheusTargetCount in avalanche values.
    #
    # To increase the sample ingestion rate, decrease serviceMonitor.interval
    # value from avalanche values based the following formula,
    #
    # interval = Desired Active Series / Desired Sample rate
    # e.g. To get 2M active series, increase fakePrometheusTargetCount to 4 and
    # to get 50K samples/s set the serviceMonitor.interval to 40s (i.e. 2M/50K)
    - --metric-count=5000
    - --series-count=100
    - --label-count=1
    - --value-interval=30
  # resources:
  #   requests:
  #     cpu: 200m
  #     memory: 2Gi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/component
              operator: In
              values:
              - timescaledb
          topologyKey: "kubernetes.io/hostname"
