{
 "title": "Promscale",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (version, branch, instance, job) (promscale_build_info)"
    }
   ]
  },
  {
   "title": "Samples Ingest Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by (kind) (rate(promscale_ingest_items_total[$__rate_interval]))",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  {
   "title": "Compression status",
   "type": "stat",
   "description": "Database compression status. If at least one promecale connector reports compression being disabled, this panel should turn red.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(promscale_sql_database_compression_status)"
    }
   ]
  },
  {
   "title": "Ingest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (HTTP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(promscale_ingest_requests_total[$__rate_interval]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Errors (HTTP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(promscale_ingest_requests_total{code=~\"5..\"}[$__rate_interval]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Duration (HTTP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(promscale_ingest_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "p50 {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.90, rate(promscale_ingest_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "p90 {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.90, rate(promscale_ingest_duration_seconds_bucket[$__rate_interval]))",
       "legendFormat": "p95 {{ type }}"
      }
     ]
    },
    {
     "title": "Requests (gRPC)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(grpc_server_handled_total{grpc_service=~\"opentelemetry.proto.collector.trace.v1.TraceService\",grpc_method=~\"Export\"}[$__rate_interval]) > 0",
       "legendFormat": "{{ grpc_type }}"
      }
     ]
    },
    {
     "title": "Errors (gRPC)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(grpc_server_handled_total{grpc_service=~\"opentelemetry.proto.collector.trace.v1.TraceService\",grpc_code=~\"Aborted|Unavailable|Internal|Unknown|Unimplemented|DataLoss\",grpc_method=~\"Export\"}[$__rate_interval])",
       "legendFormat": "{{ grpc_code }}"
      }
     ]
    },
    {
     "title": "Duration (gRPC)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(grpc_server_handling_seconds_bucket{grpc_service=\"opentelemetry.proto.collector.trace.v1.TraceService\",grpc_method=~\"Export\"}[$__rate_interval]))",
       "legendFormat": "p50 {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.5, rate(grpc_server_handling_seconds_bucket{grpc_service=\"opentelemetry.proto.collector.trace.v1.TraceService\",grpc_method=~\"Export\"}[$__rate_interval]))",
       "legendFormat": "p90 {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.5, rate(grpc_server_handling_seconds_bucket{grpc_service=\"opentelemetry.proto.collector.trace.v1.TraceService\",grpc_method=~\"Export\"}[$__rate_interval]))",
       "legendFormat": "p95 {{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests (HTTP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(promscale_query_requests_total[$__rate_interval]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Errors (HTTP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (type) (rate(promscale_query_requests_total{code=~\"5..\"}[$__rate_interval]))",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Duration (HTTP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le, instance, job) (rate(promscale_query_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le, instance, job) (rate(promscale_query_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Last maintenance job status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(promscale_sql_database_worker_maintenance_job_failed)"
    }
   ]
  },
  {
   "title": "Compressed Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "min by (job, instance) (promscale_sql_database_chunks_compressed_count)\n/\nmax by (job, instance)(promscale_sql_database_chunks_count)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Database health",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - promscale_sql_database_health_check_errors_total / promscale_sql_database_health_check_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Last DB maintenance job start",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(promscale_sql_database_worker_maintenance_job_start_timestamp_seconds) * 1000"
    }
   ]
  },
  {
   "title": "Duration (query)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(promscale_database_requests_duration_seconds_bucket{method=~\"query.*\"}[$__rate_interval]))",
     "legendFormat": "p50 - {{ method }}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(promscale_database_requests_duration_seconds_bucket{method=~\"query.*\"}[$__rate_interval]))",
     "legendFormat": "p90 - {{ method }}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(promscale_database_requests_duration_seconds_bucket{method=~\"query.*\"}[$__rate_interval]))",
     "legendFormat": "p95 - {{ method }}"
    }
   ]
  },
  {
   "title": "Duration (non-query)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(promscale_database_requests_duration_seconds_bucket{method!~\"query.*\"}[$__rate_interval]))",
     "legendFormat": "p50 - {{ method }}"
    },
    {
     "expr": "histogram_quantile(0.9, rate(promscale_database_requests_duration_seconds_bucket{method!~\"query.*\"}[$__rate_interval]))",
     "legendFormat": "p90 - {{ method }}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(promscale_database_requests_duration_seconds_bucket{method!~\"query.*\"}[$__rate_interval]))",
     "legendFormat": "p95 - {{ method }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(promscale_database_requests_total[$__rate_interval])",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Network latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "promscale_sql_database_network_latency_milliseconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hit ratio (metrics)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "promscale_cache_query_hits_total{type=\"metric\"} / promscale_cache_queries_total{type=\"metric\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Hit ratio (traces)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "promscale_cache_query_hits_total{type=\"trace\"} / promscale_cache_queries_total{type=\"trace\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (type, name) (rate(promscale_cache_evictions_total[$__rate_interval]))",
       "legendFormat": "{{ type }} - {{ name }}"
      }
     ]
    },
    {
     "title": "Latency (metrics)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(promscale_cache_query_latency_microseconds_bucket{type=\"metric\"}[$__rate_interval]))",
       "legendFormat": "p50 - {{ name }}"
      },
      {
       "expr": "histogram_quantile(0.90, rate(promscale_cache_query_latency_microseconds_bucket{type=\"metric\"}[$__rate_interval]))",
       "legendFormat": "p90 - {{ name }}"
      }
     ]
    },
    {
     "title": "Latency (traces)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, rate(promscale_cache_query_latency_microseconds_bucket{type=\"trace\"}[$__rate_interval]))",
       "legendFormat": "p50 {{ name }}"
      },
      {
       "expr": "histogram_quantile(0.90, rate(promscale_cache_query_latency_microseconds_bucket{type=\"trace\"}[$__rate_interval]))",
       "legendFormat": "p90 {{ name }}"
      }
     ]
    },
    {
     "title": "Occupancy",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "promscale_cache_elements / promscale_cache_capacity_elements",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  }
 ]
}